services:
  ocsv:
    container_name: ocsv
    build:
      context: .
      dockerfile: Dockerfile
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    volumes:
      - ./ocserv:/etc/ocserv:rw
    env_file: .env
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.forwarding=1
    restart: always
    stop_grace_period: 0s
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.ocsv.rule=HostSNI(`${OCSV_DOMAIN}`)"
      - "traefik.tcp.routers.ocsv.entrypoints=websecure"
      - "traefik.tcp.routers.ocsv.tls=true"
      - "traefik.tcp.routers.ocsv.tls.passthrough=true"
      - "traefik.tcp.routers.ocsv.tls.certresolver=letsencrypt"
      - "traefik.tcp.routers.ocsv.service=ocsv"
      - "traefik.tcp.services.ocsv.loadbalancer.server.port=443"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"

  certdumper:
    image: humenius/traefik-certs-dumper
    network_mode: none
    command: --restart-containers ocsv
    volumes:
      - /root/docker-setups/traefik/certs/acme.json:/traefik/acme.json:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./ocserv/certs:/output:rw
    environment:
      - DOMAIN=${OCSV_DOMAIN}
    restart: always
    stop_grace_period: 0s

networks:
  default:
    name: web
    external: true
